name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  compile-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Local Git
        run: |
          git config --global user.email "ryanmarks151@gmail.com"
          git config --global user.name "Ryan Marks"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
